Repository Team-MOISAM/moisam-server, pull requests merged in 2025-08, with the labels that each got.

#139 [SPOT-148] 모임 수정 및 삭제하기
  src/main/java/com/meetup/server/event/application/EventService.java
  src/main/java/com/meetup/server/event/domain/Event.java
  src/main/java/com/meetup/server/event/dto/request/EventRequest.java
  src/main/java/com/meetup/server/event/dto/request/UpdateEventRequest.java
  src/main/java/com/meetup/server/event/dto/response/MeetingPointRoutesResponse.java
  src/main/java/com/meetup/server/event/implement/EventProcessor.java
  src/main/java/com/meetup/server/event/presentation/EventController.java
  src/main/java/com/meetup/server/review/domain/Review.java
  src/main/java/com/meetup/server/review/implement/ReviewWriter.java
  src/main/java/com/meetup/server/review/persistence/ReviewRepository.java
  src/main/java/com/meetup/server/startpoint/implement/StartPointProcessor.java
  src/main/java/com/meetup/server/startpoint/persistence/StartPointRepository.java
Labels: ♻️ refactor, ✨ feat, D-0

#140 [SPOT-132] MP 조회 시, 확정 장소 데이터를 추가 반환하기
  src/main/java/com/meetup/server/event/application/EventCacheService.java
  src/main/java/com/meetup/server/event/dto/response/MeetingPointRoutesResponse.java
  src/main/java/com/meetup/server/event/implement/EventReader.java
  src/main/java/com/meetup/server/global/util/TimeUtil.java
  src/main/java/com/meetup/server/place/application/PlaceService.java
  src/main/java/com/meetup/server/user/dto/response/UserEventHistoryResponse.java
Labels: D-0

#143 [SPOT-160] HI 1명 조회 가능하게 변경하기
  src/main/java/com/meetup/server/startpoint/persistence/StartPointCustomRepositoryImpl.java
Labels: ✨ feat, D-0

#148 [SPOT-175] 경로 NPE 방지를 위해 Optional로 처리하기
  src/main/java/com/meetup/server/batch/place/job/PlaceSaveJob.java
  src/main/java/com/meetup/server/event/dto/response/route/DrivingInfoResponse.java
  src/main/java/com/meetup/server/event/dto/response/route/DrivingRouteResponse.java
  src/main/java/com/meetup/server/event/dto/response/route/TransitRouteResponse.java
  src/main/java/com/meetup/server/event/implement/route/RouteApiCaller.java
  src/main/java/com/meetup/server/event/implement/route/RouteProcessor.java
  src/main/java/com/meetup/server/place/domain/Place.java
  src/main/java/com/meetup/server/place/dto/response/PlaceDetailResponse.java
Labels: ♻️ refactor, D-0
