Repository Team-MOISAM/moisam-server, pull requests merged in 2025-07, with the labels that each got.

#127 [SPOT-37] 출발지 정보를 수정 및 삭제한다
  src/main/java/com/meetup/server/event/implement/EventProcessor.java
  src/main/java/com/meetup/server/startpoint/application/StartPointService.java
  src/main/java/com/meetup/server/startpoint/domain/StartPoint.java
  src/main/java/com/meetup/server/startpoint/exception/StartPointErrorType.java
  src/main/java/com/meetup/server/startpoint/implement/StartPointProcessor.java
  src/main/java/com/meetup/server/startpoint/implement/StartPointReader.java
  src/main/java/com/meetup/server/startpoint/implement/StartPointValidator.java
  src/main/java/com/meetup/server/startpoint/presentation/StartPointController.java
  src/test/java/com/meetup/server/startpoint/application/StartPointServiceTest.java
Labels: ✨ feat, D-0

#131 [SPOT-129] 히스토리 조회 시 모임명, 모임날짜 및 시간을 추가로 반환하기
  src/main/java/com/meetup/server/global/util/TimeUtil.java
  src/main/java/com/meetup/server/startpoint/persistence/StartPointCustomRepositoryImpl.java
  src/main/java/com/meetup/server/startpoint/persistence/projection/EventHistory.java
  src/main/java/com/meetup/server/user/dto/response/UserEventHistoryResponse.java
  src/main/java/com/meetup/server/user/implement/UserEventHistoryAssembler.java
Labels: ♻️ refactor, ✨ feat, D-1

#133 [SPOT-131] PL 조회 시 모임 명 추가한다
  src/main/java/com/meetup/server/place/application/PlaceService.java
  src/main/java/com/meetup/server/place/dto/response/PlaceResponseList.java
  src/main/java/com/meetup/server/place/presentation/PlaceController.java
Labels: ✨ feat, D-1

#132 [SPOT-130] 대중교통 선택 여부 기반으로 상세 경로 조회하기
  src/main/java/com/meetup/server/event/application/EventCacheService.java
  src/main/java/com/meetup/server/event/domain/Event.java
  src/main/java/com/meetup/server/event/dto/response/DrivingInfoResponse.java
  src/main/java/com/meetup/server/event/dto/response/DrivingRouteResponse.java
  src/main/java/com/meetup/server/event/dto/response/MeetingPointRouteGroup.java
  src/main/java/com/meetup/server/event/dto/response/MeetingPointRoutesResponse.java
  src/main/java/com/meetup/server/event/dto/response/RouteResponse.java
  src/main/java/com/meetup/server/event/implement/EventProcessor.java
  src/main/java/com/meetup/server/event/implement/MeetingPointCalculator.java
  src/main/java/com/meetup/server/event/implement/RouteAssembler.java
  src/main/java/com/meetup/server/event/implement/RouteDetailFetcher.java
  src/main/java/com/meetup/server/event/presentation/EventController.java
  src/main/java/com/meetup/server/startpoint/exception/StartPointErrorType.java
  src/main/java/com/meetup/server/startpoint/implement/StartPointReader.java
  src/main/java/com/meetup/server/startpoint/persistence/StartPointRepository.java
Labels: ♻️ refactor, ✨ feat, D-0
