Repository Team-MOISAM/moisam-server, pull requests merged in 2025-05, with the labels that each got.

#24 FEAT: #23 로그아웃 구현하기
  src/main/java/com/meetup/server/auth/application/AuthService.java
  src/main/java/com/meetup/server/auth/presentation/AuthController.java
  src/main/java/com/meetup/server/auth/presentation/filter/ResponseContextFilter.java
  src/main/java/com/meetup/server/auth/support/CookieProperties.java
  src/main/java/com/meetup/server/auth/support/CookieUtil.java
  src/main/java/com/meetup/server/auth/support/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/meetup/server/global/config/ConfigurationPropertiesConfig.java
  src/main/java/com/meetup/server/user/domain/User.java
  src/main/java/com/meetup/server/user/dto/response/UserProfileInfoResponse.java
  src/main/java/com/meetup/server/user/persistence/init/UserDummy.java
  src/test/java/com/meetup/server/event/implement/EventProcessorTest.java
  src/test/java/com/meetup/server/user/application/UserServiceTest.java
Labels: ✨ feat, 📦 chore

#28 FEAT: #21 사용자 출발지 등록 API
  src/main/java/com/meetup/server/event/application/EventService.java
  src/main/java/com/meetup/server/event/domain/Event.java
  src/main/java/com/meetup/server/event/dto/response/EventStartPointResponse.java
  src/main/java/com/meetup/server/event/exception/EventErrorType.java
  src/main/java/com/meetup/server/event/exception/EventException.java
  src/main/java/com/meetup/server/event/implement/EventProcessor.java
  src/main/java/com/meetup/server/event/implement/EventReader.java
  src/main/java/com/meetup/server/event/implement/EventValidator.java
  src/main/java/com/meetup/server/event/presentation/EventController.java
  src/main/java/com/meetup/server/global/config/SecurityConfig.java
  src/main/java/com/meetup/server/startpoint/application/StartPointService.java
  src/main/java/com/meetup/server/startpoint/domain/StartPoint.java
  src/main/java/com/meetup/server/startpoint/domain/type/Address.java
  src/main/java/com/meetup/server/startpoint/domain/type/Location.java
  src/main/java/com/meetup/server/startpoint/implement/StartPointProcessor.java
  src/main/java/com/meetup/server/startpoint/persistence/StartPointRepository.java
  src/main/java/com/meetup/server/startpoint/presentation/StartPointController.java
  src/test/java/com/meetup/server/event/application/EventServiceTest.java
  src/test/java/com/meetup/server/event/implement/EventProcessorTest.java
  src/test/java/com/meetup/server/event/implement/EventValidatorTest.java
  src/test/java/com/meetup/server/fixture/EventFixture.java
  src/test/java/com/meetup/server/fixture/StartPointFixture.java
  src/test/java/com/meetup/server/startpoint/application/StartPointServiceTest.java
Labels: 🐛 fix, 🧪 test, ✨ feat

#45 FEAT: #44 출발지 저장 시 isUser, nonUserName 신규 필드도 함께 저장한다
  src/main/java/com/meetup/server/event/application/RouteService.java
  src/main/java/com/meetup/server/startpoint/implement/StartPointProcessor.java
Labels: 🐛 fix, ✨ feat

#51 FEAT: #50 accessToken 의 처리를 변경한다
  src/main/java/com/meetup/server/auth/presentation/filter/JwtAuthenticationFilter.java
  src/main/java/com/meetup/server/auth/support/CookieUtil.java
Labels: ✨ feat

#49 FEAT: #46 사용자 약관 동의 항목을 저장하기
  src/main/java/com/meetup/server/global/config/SecurityConfig.java
  src/main/java/com/meetup/server/user/application/UserService.java
  src/main/java/com/meetup/server/user/domain/User.java
  src/main/java/com/meetup/server/user/dto/request/UserAgreementRequest.java
  src/main/java/com/meetup/server/user/dto/response/UserProfileInfoResponse.java
  src/main/java/com/meetup/server/user/exception/UserErrorType.java
  src/main/java/com/meetup/server/user/implement/AgreementValidator.java
  src/main/java/com/meetup/server/user/persistence/init/UserDummy.java
  src/main/java/com/meetup/server/user/presentation/UserController.java
Labels: ✨ feat

#52 FEAT: #50 JWTFilter 로직을 수정한다
  src/main/java/com/meetup/server/auth/presentation/filter/JwtAuthenticationFilter.java
  src/main/java/com/meetup/server/global/config/SecurityConfig.java
Labels: ✨ feat

#57 FEAT: #55 대중교통 여부를 토대로 기존 캐시 수정하기
  src/main/java/com/meetup/server/event/application/EventCacheService.java
  src/main/java/com/meetup/server/event/application/EventMapFacadeService.java
  src/main/java/com/meetup/server/event/application/EventService.java
  src/main/java/com/meetup/server/event/application/RouteDetailService.java
  src/main/java/com/meetup/server/event/application/RouteService.java
  src/main/java/com/meetup/server/event/dto/response/RouteResponse.java
  src/main/java/com/meetup/server/event/dto/response/RouteResponseList.java
  src/main/java/com/meetup/server/event/exception/EventErrorType.java
  src/main/java/com/meetup/server/event/implement/EventProcessor.java
  src/main/java/com/meetup/server/event/implement/EventReader.java
  src/main/java/com/meetup/server/event/implement/EventValidator.java
  src/main/java/com/meetup/server/event/presentation/EventController.java
  src/main/java/com/meetup/server/startpoint/implement/StartPointProcessor.java
Labels: 🐛 fix, ✨ feat

#59 FEAT: #56 출발지 등록 시 비회원 방식으로 처리 하고 캐시 무효화를 진행한다
  src/main/java/com/meetup/server/startpoint/application/StartPointService.java
  src/test/java/com/meetup/server/event/application/EventServiceTest.java
  src/test/java/com/meetup/server/event/implement/EventValidatorTest.java
  src/test/java/com/meetup/server/startpoint/application/StartPointServiceTest.java
  src/test/java/com/meetup/server/support/IntegrationTestContainer.java
Labels: ✨ feat

#67 FEAT: #63 모임생성자를 추가한다
  src/main/java/com/meetup/server/event/application/EventCacheService.java
  src/main/java/com/meetup/server/event/application/RouteDetailService.java
  src/main/java/com/meetup/server/event/application/RouteService.java
  src/main/java/com/meetup/server/event/dto/response/RouteResponseList.java
  src/main/java/com/meetup/server/event/persistence/EventRepository.java
  src/main/java/com/meetup/server/startpoint/implement/StartPointReader.java
  src/main/java/com/meetup/server/startpoint/persistence/StartPointRepository.java
Labels: ✨ feat

#68 FIX: #65 출발지 검색 시 서울 지역만 검색되도록 필터링한다
  src/main/java/com/meetup/server/global/clients/kakao/local/KakaoLocalResponse.java
  src/main/java/com/meetup/server/startpoint/application/StartPointService.java
  src/main/java/com/meetup/server/startpoint/implement/StartPointSearcher.java
  src/test/java/com/meetup/server/global/clients/kakao/local/KakaoLocalClientTest.java
Labels: 🐛 fix

#77 FIX: #76 리뷰 엔티티 수정하기
  src/main/java/com/meetup/server/review/domain/NonVisitedReason.java
  src/main/java/com/meetup/server/review/domain/NonVisitedReview.java
  src/main/java/com/meetup/server/review/domain/Review.java
  src/main/java/com/meetup/server/review/domain/Satisfaction.java
  src/main/java/com/meetup/server/review/domain/VisitedReview.java
  src/main/java/com/meetup/server/review/domain/type/NonVisitedReasonCategory.java
  src/main/java/com/meetup/server/review/domain/type/ScoreCategory.java
  src/main/java/com/meetup/server/review/domain/type/VisitedTime.java
  src/main/java/com/meetup/server/review/domain/value/ActualVisitedPlace.java
  src/main/java/com/meetup/server/review/domain/value/PlaceRating.java
  src/main/java/com/meetup/server/review/persistence/NonVisitedReviewRepository.java
  src/main/java/com/meetup/server/review/persistence/ReviewRepository.java
  src/main/java/com/meetup/server/review/persistence/VisitedReviewRepository.java
Labels: 🐛 fix

#74 FEAT: #70 로그인 사용자의 참여한 모임 목록 조회하기
  src/main/java/com/meetup/server/auth/application/AuthService.java
  src/main/java/com/meetup/server/auth/support/CookieProperties.java
  src/main/java/com/meetup/server/auth/support/CookieUtil.java
  src/main/java/com/meetup/server/event/application/MiddlePointService.java
  src/main/java/com/meetup/server/global/util/TimeUtil.java
  src/main/java/com/meetup/server/place/persistence/init/PlaceDummy.java
  src/main/java/com/meetup/server/review/domain/Review.java
  src/main/java/com/meetup/server/review/domain/VisitedReview.java
  src/main/java/com/meetup/server/review/domain/value/PlaceRating.java
  src/main/java/com/meetup/server/review/implement/ReviewChecker.java
  src/main/java/com/meetup/server/review/implement/ReviewReader.java
  src/main/java/com/meetup/server/review/persistence/ReviewRepository.java
  src/main/java/com/meetup/server/review/persistence/init/ReviewDummy.java
  src/main/java/com/meetup/server/startpoint/application/StartPointService.java
  src/main/java/com/meetup/server/startpoint/implement/ParticipantExtractor.java
  src/main/java/com/meetup/server/startpoint/implement/StartPointReader.java
  src/main/java/com/meetup/server/startpoint/persistence/StartPointRepository.java
  src/main/java/com/meetup/server/user/application/UserService.java
  src/main/java/com/meetup/server/user/dto/response/UserEventHistoryResponse.java
  src/main/java/com/meetup/server/user/dto/response/UserEventHistoryResponseList.java
  src/main/java/com/meetup/server/user/implement/UserEventHistoryAssembler.java
  src/main/java/com/meetup/server/user/implement/UserReader.java
  src/main/java/com/meetup/server/user/presentation/UserController.java
Labels: ✨ feat

#82 FEAT: #73 추천 장소 리스트 조회하기
  src/main/java/com/meetup/server/event/domain/Event.java
  src/main/java/com/meetup/server/global/util/TimeUtil.java
  src/main/java/com/meetup/server/place/application/PlaceService.java
  src/main/java/com/meetup/server/place/domain/Place.java
  src/main/java/com/meetup/server/place/domain/value/GoogleReview.java
  src/main/java/com/meetup/server/place/domain/value/OpeningHour.java
  src/main/java/com/meetup/server/place/dto/response/PlaceResponse.java
  src/main/java/com/meetup/server/place/dto/response/PlaceResponseList.java
  src/main/java/com/meetup/server/place/implement/PlaceProcessor.java
  src/main/java/com/meetup/server/place/implement/PlaceReader.java
  src/main/java/com/meetup/server/place/implement/PlaceSorter.java
  src/main/java/com/meetup/server/place/persistence/PlaceRepository.java
  src/main/java/com/meetup/server/place/persistence/projection/PlaceWithDistance.java
  src/main/java/com/meetup/server/place/presentation/PlaceController.java
  src/main/java/com/meetup/server/review/domain/VisitedReview.java
  src/main/java/com/meetup/server/review/domain/value/PlaceScore.java
  src/main/java/com/meetup/server/review/implement/ReviewReader.java
  src/main/java/com/meetup/server/review/persistence/VisitedReviewRepository.java
  src/main/java/com/meetup/server/review/persistence/init/ReviewDummy.java
  src/main/java/com/meetup/server/review/persistence/projection/PlaceWithRating.java
Labels: ✨ feat

#85 FEAT: #83 장소 리뷰 작성하기
  src/main/java/com/meetup/server/review/application/ReviewService.java
  src/main/java/com/meetup/server/review/domain/NonVisitedReview.java
  src/main/java/com/meetup/server/review/domain/Review.java
  src/main/java/com/meetup/server/review/dto/request/NonVisitedReviewRequest.java
  src/main/java/com/meetup/server/review/dto/request/VisitedReviewRequest.java
  src/main/java/com/meetup/server/review/exception/ReviewErrorType.java
  src/main/java/com/meetup/server/review/exception/ReviewException.java
  src/main/java/com/meetup/server/review/implement/ReviewValidator.java
  src/main/java/com/meetup/server/review/implement/ReviewWriter.java
  src/main/java/com/meetup/server/review/persistence/ReviewRepository.java
  src/main/java/com/meetup/server/review/presentation/ReviewController.java
Labels: ✨ feat

#86 FEAT: #81 장소 상세 조회를 진행한다
  src/main/java/com/meetup/server/event/domain/Event.java
  src/main/java/com/meetup/server/place/application/PlaceService.java
  src/main/java/com/meetup/server/place/dto/response/GoogleReviewResponse.java
  src/main/java/com/meetup/server/place/dto/response/PlaceDetailResponse.java
  src/main/java/com/meetup/server/place/dto/response/PlaceQuietnessResponse.java
  src/main/java/com/meetup/server/place/dto/response/ReviewResponse.java
  src/main/java/com/meetup/server/place/implement/PlaceSorter.java
  src/main/java/com/meetup/server/place/presentation/PlaceController.java
  src/main/java/com/meetup/server/review/implement/ReviewReader.java
  src/main/java/com/meetup/server/review/persistence/VisitedReviewRepository.java
  src/main/java/com/meetup/server/review/persistence/init/ReviewDummy.java
  src/main/java/com/meetup/server/review/persistence/projection/PlaceQuietnessWithRating.java
  src/main/java/com/meetup/server/user/dto/response/UserEventHistoryResponse.java
Labels: ✨ feat

#88 FEAT: #87 리뷰 작성 시 장소 정보 보여주기
  src/main/java/com/meetup/server/place/application/PlaceService.java
  src/main/java/com/meetup/server/place/dto/response/PlaceResponseList.java
  src/main/java/com/meetup/server/place/presentation/PlaceController.java
Labels: ✨ feat

#91 FIX: #90 구글 평점이 없는 장소 정렬 시 NPE 발생 방지를 위해 null-safe하게 처리하기
  src/main/java/com/meetup/server/place/implement/PlaceSorter.java
Labels: 🐛 fix

#95 FIX: #94 방문하지 않은 리뷰를 작성한 경우에도 상세 조회가 가능하도록 하기
  src/main/java/com/meetup/server/place/dto/response/ReviewResponse.java
Labels: 🐛 fix

#93 FEAT: #89 자가용 상세 경로 좌표 반환하기
  src/main/java/com/meetup/server/event/application/RouteDetailService.java
  src/main/java/com/meetup/server/event/application/RouteService.java
  src/main/java/com/meetup/server/event/dto/response/DrivingInfoResponse.java
  src/main/java/com/meetup/server/event/dto/response/DrivingRouteResponse.java
  src/main/java/com/meetup/server/event/dto/response/ParkingLotResponse.java
  src/main/java/com/meetup/server/event/dto/response/RouteResponse.java
  src/main/java/com/meetup/server/event/dto/response/RouteResponseList.java
  src/main/java/com/meetup/server/global/util/Coordinate.java
  src/main/java/com/meetup/server/parkinglot/implement/ParkingLotFinder.java
  src/main/java/com/meetup/server/parkinglot/persistence/ParkingLotRepository.java
  src/main/java/com/meetup/server/parkinglot/persistence/projection/ClosestParkingLot.java
  src/main/java/com/meetup/server/startpoint/util/RouteExtractor.java
Labels: ✨ feat

#92 FIX: #80 사용자 모임 히스토리 조회 시 무한 스크롤 반영 및 0시간 인 경우와 모임 1인 인 경우 수정 사항 반영하기
  src/main/java/com/meetup/server/global/util/TimeUtil.java
  src/main/java/com/meetup/server/review/implement/ReviewChecker.java
  src/main/java/com/meetup/server/review/implement/ReviewReader.java
  src/main/java/com/meetup/server/review/persistence/ReviewCustomRepository.java
  src/main/java/com/meetup/server/review/persistence/ReviewCustomRepositoryImpl.java
  src/main/java/com/meetup/server/review/persistence/ReviewRepository.java
  src/main/java/com/meetup/server/startpoint/implement/StartPointReader.java
  src/main/java/com/meetup/server/startpoint/persistence/StartPointCustomRepository.java
  src/main/java/com/meetup/server/startpoint/persistence/StartPointCustomRepositoryImpl.java
  src/main/java/com/meetup/server/startpoint/persistence/StartPointRepository.java
  src/main/java/com/meetup/server/startpoint/persistence/projection/EventHistory.java
  src/main/java/com/meetup/server/startpoint/persistence/projection/Participant.java
  src/main/java/com/meetup/server/startpoint/persistence/projection/ParticipantCount.java
  src/main/java/com/meetup/server/user/application/UserService.java
  src/main/java/com/meetup/server/user/dto/response/UserEventHistoryResponse.java
  src/main/java/com/meetup/server/user/dto/response/UserEventHistoryResponseList.java
  src/main/java/com/meetup/server/user/implement/UserEventHistoryAssembler.java
  src/main/java/com/meetup/server/user/presentation/UserController.java
Labels: 🐛 fix

#100 FIX: (#99) 모임 조회 쿼리를 수정한다
  src/main/java/com/meetup/server/startpoint/persistence/StartPointCustomRepositoryImpl.java
  src/main/java/com/meetup/server/user/implement/UserEventHistoryAssembler.java
Labels: 🐛 fix

#101 FEAT: #98 사용자 닉네임 변경 및 사용자 탈퇴를 진행하기
  src/main/java/com/meetup/server/user/application/UserService.java
  src/main/java/com/meetup/server/user/domain/User.java
  src/main/java/com/meetup/server/user/implement/UserWriter.java
  src/main/java/com/meetup/server/user/persistence/UserCustomRepository.java
  src/main/java/com/meetup/server/user/persistence/UserCustomRepositoryImpl.java
  src/main/java/com/meetup/server/user/persistence/UserRepository.java
  src/main/java/com/meetup/server/user/presentation/UserController.java
Labels: ✨ feat

#114 FIX: #113 리뷰 조회에서 eventId 를 고려하도록 변경하기
  src/main/java/com/meetup/server/auth/support/resolver/CustomAuthorizationRequestResolver.java
  src/main/java/com/meetup/server/review/application/ReviewService.java
  src/main/java/com/meetup/server/review/domain/Review.java
  src/main/java/com/meetup/server/review/implement/ReviewValidator.java
  src/main/java/com/meetup/server/review/implement/ReviewWriter.java
  src/main/java/com/meetup/server/review/persistence/ReviewCustomRepositoryImpl.java
  src/main/java/com/meetup/server/review/persistence/ReviewRepository.java
  src/main/java/com/meetup/server/review/persistence/init/ReviewDummy.java
  src/main/java/com/meetup/server/review/presentation/ReviewController.java
Labels: 🐛 fix

#110 FEAT: #106 API Rate Limiter로 API 호출 관리하기
  src/main/java/com/meetup/server/global/clients/exception/ClientErrorType.java
  src/main/java/com/meetup/server/global/clients/exception/ClientException.java
  src/main/java/com/meetup/server/global/clients/kakao/mobility/KakaoMobilityClient.java
  src/main/java/com/meetup/server/global/clients/odsay/OdsayTransitRouteSearchClient.java
  src/main/java/com/meetup/server/global/clients/util/LimitRequestPerDay.java
  src/main/java/com/meetup/server/global/clients/util/RateLimiter.java
  src/main/java/com/meetup/server/global/clients/util/RateLimiterAspect.java
  src/main/java/com/meetup/server/global/clients/util/RedisRateLimiter.java
  src/main/java/com/meetup/server/global/config/RedisConfig.java
  src/main/java/com/meetup/server/global/config/RedisScriptConfig.java
  src/main/resources/scripts/rate_limit_script.lua
  src/test/java/com/meetup/server/global/clients/util/RateLimiterTest.java
  src/test/resources/scripts/rate_limit_script.lua
Labels: ✨ feat
